### ISSUE TITLE
how do I run this in Linux? 

### ISSUE THREAD

**Issue by aristosv** [calxibe/StorjMonitor#11]
can anyone explain how to run this on Linux? (Debian)
I have storj up and running, all disks are connected. I downloaded StorjMonitor-master.zip, put my API key in storjMonitor.js, chmod +x storjMonitor.sh and run it.

I get a message ./storjMonitor.sh: line 1: /usr/bin/node: No such file or directory which makes sense because /usr/bin/node does not exist.

So how do I run this?

**Comment by stefanbenten** [comment]
@aristosv Run this script:
`git clone https://github.com/calxibe/StorjMonitor.git
cd StorjMonitor
rm -rf node_modules
npm install
chmod +x storjMonitor.sh`

Edit the storjMonitor.js and insert your API Key.
Then delete the path /usr/bin/ from the storjMonitor.sh and run

`sudo apt get install screen 
screen -dmS SMonitor ./storjMonitor.sh`

**Comment by audioeng** [comment]
ust tryIf you don’t want to install screens, you can just run this...

node storjMonitor.js &

**Comment by stefanbenten** [comment]
@audioeng But then you run it on the foreground, which is unfortunate, when you want to use the system

**Comment by stefanbenten** [comment]
But how do you connect back to it?
Its just my recommendation.

**Comment by audioeng** [comment]
Yes screens can be helpful if you want to connect back to it... I can’t
think of a reason you would need to though. I just kill the process and run
it again if needed.

You can resume without screens using bg though.
https://www.systutorials.com/docs/linux/man/1p-bg/

**Comment by stefanbenten** [comment]
I would like to know why it failed to report. Just putting things into background especially for monitoring software isnt the best programming style imho.
Another smart approach can be to create a log and push it into that, then you're correct @audioeng

**Comment by audioeng** [comment]
Yes, I agree, piping output to a log is preferred.

Personally, I just added logic to send a push notification to my phone
using pushover, so I know how much data is being used.
I don’t worry about the output of the script, as
Storjstat will show a ! on your nodes page if it doesn’t report in a period
of time.

**Comment by audioeng** [comment]
node storjMonitor.js &> output.log &

Will accomplish that, send it to background and send stdin and stderr to output.log
