### ISSUE TITLE
i get error message "is not defined", windows

### ISSUE THREAD

**Issue by Limit4you** [calxibe/StorjMonitor#13]
![storj](https://user-images.githubusercontent.com/18258766/36417707-4e540fb4-1635-11e8-99a4-bfd2701803d6.JPG)

**Comment by audioeng** [comment]
Put your token in quotes.

**Comment by stefanbenten** [comment]
@Limit4you Did you get it working?

**Comment by Limit4you** [comment]
yes, it helped, thank you, but now i get new error
![storj2](https://user-images.githubusercontent.com/18258766/36522506-a2d83df0-17a5-11e8-8876-0f51d8185c8a.JPG)

**Comment by stefanbenten** [comment]
@Limit4you This is an issue from your farmer node itself. It reports ... (...%) on the GUI correct?
If yes, please follow these steps to fix it:

1. install the node.js LTS version: https://nodejs.org/en/download
2. run in command line (cmd/powershell): `npm install -g kfs@v3.0.0`
3. stop the node
4. in the command line (cmd/powershell): `kfs -d d:\storjpc\storj1\sharddata.kfs compact

**Comment by Limit4you** [comment]
![image](https://user-images.githubusercontent.com/18258766/36558171-d5e053aa-1812-11e8-8e8e-8780df5fb56e.png)

**Comment by Limit4you** [comment]
![image](https://user-images.githubusercontent.com/18258766/36558190-ed5e4c9e-1812-11e8-9958-4571db47e11d.png)

**Comment by Limit4you** [comment]
![image](https://user-images.githubusercontent.com/18258766/36558200-f5d91ba6-1812-11e8-9e89-9ab3afde1375.png)

**Comment by Limit4you** [comment]
![image](https://user-images.githubusercontent.com/18258766/36559246-1470ae3c-1816-11e8-9b00-4c732598600f.png)

Working :)))

**Comment by stefanbenten** [comment]
Awesome! Just wanted to make the step by step guide for you 👍 
Glad its working now 💯
