### ISSUE TITLE
One node reporting, the other one not.. [RaspberryPI]

### ISSUE THREAD

**Issue by ivnmad** [calxibe/StorjMonitor#15]
Following up from #6 

I created a new node and tried to run StorjMonitor again.
The new node seems to be reporting successfully, the other one doesn't:

[12:52:05] node1 | Submit to Storjstat
[12:52:05] node2 | Submit to Storjstat
[12:52:05] ERROR {"error":"Invalid farmer data (spaceUsedBytes)"}
[12:52:15] node2 | Success

Any suggestions on what might be causing that?
I presume it must be something inside the node itself, but I've got no idea what StorjMonitor looks at to get that info (I haven't looked at the actual code).

**Comment by stefanbenten** [comment]
Very easy question, does the storjshare status give you a shared value on both nodes?
If not its a fault on your node itself. Solutions is the following guide:

1. Run in shell: `npm install -g kfs@v3.0.0`
2. Stop the node
3. Back in the shell run: `kfs -d /PATH/TO/SHARE/sharddata.kfs compact`

**Comment by ivnmad** [comment]
storjshare status only shows a value on node2

I followed your instructions, it run for a bit, but then got the following error message:
[error] IO error: "/PATH/TO/SHARE/sharddata.kfs/000.s/000001.dbtmp: Read-only file systemp

Restarted the node, but because the process wasn't completed it is still not showing any value..

**Comment by stefanbenten** [comment]
Before running the command, you obviously need to change the path...

**Comment by ivnmad** [comment]
I certainly did that, I was just hiding the real path..
Here more details on what happened:

kfs -d /PATH/TO/SHARE/sharddata.kfs compact
000.s (done!)
001.s (done!)
002.s (done!)
003.s (done!)
004.s (done!)
005.s (done!)
006.s (done!)
007.s (done!)
008.s (done!)
009.s (done!)
011.s (done!)
012.s (done!)
013.s (done!)
014.s (done!)
015.s (done!)
016.s (done!)
017.s (done!)
020.s (done!)
021.s (done!)
022.s (done!)
023.s (done!)
024.s (done!)
025.s (done!)
026.s (done!)
027.s (done!)
028.s (done!)
032.s (done!)
034.s (done!)
036.s (done!)
037.s (done!)
038.s (done!)
039.s (done!)
041.s (done!)
043.s (done!)
044.s (done!)
045.s (done!)
047.s (done!)
048.s (done!)
049.s (done!)
050.s (done!)
051.s (done!)
052.s (done!)
053.s (done!)
054.s (done!)
055.s (done!)
056.s (done!)
057.s (done!)
058.s (done!)
059.s (done!)
060.s (done!)
062.s (done!)
063.s (done!)
065.s (done!)
066.s (done!)
067.s (done!)
068.s (done!)
[error] IO error:

**Comment by stefanbenten** [comment]
Did you stop the node before? Then you should not have a tmp file.
If you still have this file, please delete it.

**Comment by ivnmad** [comment]
Yes, I did stop it.. If I look inside the directory, there is no such file..

~/sharddata.kfs/000.s $ ls -l
-rw-r--r-- 1 pi pi    16 Feb 23 13:15 CURRENT
-rw-r--r-- 1 pi pi     0 Feb 14 12:24 LOCK
-rw-r--r-- 1 pi pi   431 Feb 23 13:15 LOG
-rw-r--r-- 1 pi pi   163 Feb 23 12:20 LOG.old
drwxr-xr-x 2 pi pi 32768 Feb 23 13:15 lost
-rw-r--r-- 1 pi pi    41 Feb 23 13:15 MANIFEST-000001

**Comment by stefanbenten** [comment]
Can you rerun the command and paste the complete output including the all paths please?

**Comment by ivnmad** [comment]
While the first time it stopped after 068.s, when I try to rerun it, it now stops immediately:

pi@RaspberryPi:~ $ kfs -d /media/pi/Storj/sharddata.kfs compact
[error] IO error: /media/pi/Storj/sharddata.kfs/000.s/000001.dbtmp: Read-only file system

The same identical command was run the first time, with everything going fine up to 0.68s (see above).

**Comment by stefanbenten** [comment]
And where does your second node reside in? Same folder?

**Comment by ivnmad** [comment]
The second node is a separate HD, so different folder..

**Comment by stefanbenten** [comment]
How much did you share with the first node?

**Comment by ivnmad** [comment]
First node is 50GB, second node is 450GB
If I run Storj_Farmer_Contracts.js on node1 it shows: "TotalGB": 1.6272597659999988
I tried to run send_storj_reports with Storjdash and it's reporting correctly.

**Comment by stefanbenten** [comment]
Can you please restart the PI? And run the script without starting StorjShare?

**Comment by ivnmad** [comment]
That worked..  "kfs -d /media/pi/Storj/sharddata.kfs compact" run to the end

Unfortunately after starting storjshare, the problem persists.

storjshare status only shows "Shared" for the second node and ./storjMonitor.sh 

[13:56:57] cdfd2e4cece475abb29970a956378c07673c99c5 | Submit to Storjstat
[13:56:57] fa0e00f2e47ef45d0319beafb153856e8c1c1529 | Submit to Storjstat
[13:56:57] ERROR {"error":"Invalid farmer data (spaceUsedBytes)"}
[13:57:02] fa0e00f2e47ef45d0319beafb153856e8c1c1529 | Success

**Comment by stefanbenten** [comment]
Okay, then its definitly an issue from the node itself and not a fault of the Monitor.
Please head over to the support forum over at community.storj.io and ask for help fixing the node problem.
Thank you!
