### ISSUE TITLE
storjMonitor.sh hangs..

### ISSUE THREAD

**Issue by ivnmad** [calxibe/StorjMonitor#16]
I finally managed to run storjMonitor.sh successfully.

./storjMonitor.sh 
[17:22:03] cdfd2e4cece475abb29970a956378c07673c99c5 | Submit to Storjstat
[17:22:03] fa0e00f2e47ef45d0319beafb153856e8c1c1529 | Submit to Storjstat
[17:22:04] cdfd2e4cece475abb29970a956378c07673c99c5 | Success
[17:22:04] fa0e00f2e47ef45d0319beafb153856e8c1c1529 | Success

At the end it just hangs in there, and I need to stop the script with CTRL+C

**Comment by stefanbenten** [comment]
The scripts checks every 15 minutes.. Thats why i recommend to run it in a screen, like shown on the README 👍

**Comment by ivnmad** [comment]
Got it.. screen dmS StorjMonitor ./storjMonitor.sh doesn't work on RaspberriPI, I probably need to install something. Otherwise I'll figure something out.. Thank you.

**Comment by stefanbenten** [comment]
You need to install screen first via `sudo apt instal screen`

**Comment by ivnmad** [comment]
OK, did that.. Now when I do screen dms StorjMonitor ./storjMonitor.sh it flashes for 1 second and then I get [screen is terminating] and back to the prompt..

**Comment by stefanbenten** [comment]
Do you add the - in front of dmS ?
Just copy paste my lines above and it should work.

**Comment by ivnmad** [comment]
I didn't have a - because it's not in the README.. 
"screen -dmS StorjMonitor ./storjMonitor.sh" seem to have worked (I just got to the prompt straight away, and I presume the monitor is running in the background)..

**Comment by ivnmad** [comment]
Not in the README.md, but I can see it in the instructions.
We should be good.. Thank you for all your help..

**Comment by stefanbenten** [comment]
Oh yes, good catch, already fixed.
You can attach to see the screen by typing: `screen -r StorjMonitor` and leave it with pressing CTRL + A and afterwards D for detaching from it. It will keep running in the background this way.

**Comment by ivnmad** [comment]
Nice.. It works.. I'm creating  a cron job to start automatically when I reboot..

**Comment by stefanbenten** [comment]
Keep in mind that StorjShare's Daemon should run before executing the StorjMonitor Service.
If you dont have any additional questions regarding this issue, feel free to close it 💯
