### ISSUE TITLE
Change token after first start

### ISSUE THREAD

**Issue by knusperkai** [calxibe/StorjMonitor#17]
Hello,
I am running StorjMonitor on Ubuntu.

I changed my API-key on StorjStat, now Im trying to do the same inside the storjMonitor.js but it’s still “connecting” by using the old token.

Even reinstall the monitor does not help.

What I am supposed to do?

Thank in advance

**Comment by stefanbenten** [comment]
How do you tell which Token is being used?
Can you please provide some more logs or information about how you determine that this is the case?

**Comment by knusperkai** [comment]
If I start the service I get the following output:

~/StorjMonitor$ ./storjMon
itor.sh                                          
[16:32:55] 519737fcc7****
 | Submit to Storjstat                         
[16:33:00] 519737fcc7*** | Success

But this token isn't my actual created token on Storjstat

**Comment by stefanbenten** [comment]
Thats youre NodeID isnt it?

**Comment by knusperkai** [comment]
Oh man. You are right....
My Node ID starts with the same 2 digits. Like the old token.

So my problem is soluted. Thanks a lot!! 

Best regards
