### ISSUE TITLE
Port in new version

### ISSUE THREAD

**Issue by xorgkc** [calxibe/StorjMonitor#22]
Looks like the March version asks for IP and port but can only handle one port number.  I have 4 nodes on one PC.  Is there a way to config with multiple nodes in same script?

**Comment by stefanbenten** [comment]
This is an config option to check the Daemon on a remote server, not the individual node.
Thus you dont need to worry about it, if you run it on the same PC!

The IP and Port you **can** configure is only for the connection to the daemon, which manages your nodes. The Monitor still works with mulitple nodes as before!
