### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by phithor** [calxibe/StorjMonitor#25]
I am getting a plain error message when running StorjMonitor inside a docker image with both storjshare and StorjMonitor inside. 

Log output:

[10:03:01] nodeid1| Submit to Storjstat
[10:03:01] nodeid2| Submit to Storjstat
[10:03:01] nodeid3| Submit to Storjstat
[10:03:01] nodeid4| Submit to Storjstat
[10:03:01] nodeid1| Error
[10:03:02] nodeid2| Error
[10:03:02] nodeid3| Error
[10:03:02] nodeid4| Error

Any clues to what could cause this?

**Comment by stefanbenten** [comment]
@phithor Do you have a complete log from that error?

**Comment by mirnyyy** [comment]
I have the same:
[10:44:27] 8a8ac13a07ab073be34db8a083c1b34a3ef0e59a | Submit to Storjstat
[10:44:27] fe89ba1415839f7acbf74f335c4a9f81f76097bb | Submit to Storjstat
[10:44:27] 984acad726f809fb310208f17e83f81f86c27b54 | Submit to Storjstat
[10:44:27] 0ceeaa46936b939ad0a2eca1b8ee0e5ae854c8f5 | Submit to Storjstat
[10:44:27] e264c56808c7bca4f54f606d16c923982d8653e8 | Submit to Storjstat
[10:44:27] 984acad726f809fb310208f17e83f81f86c27b54 | Error
[10:44:27] fe89ba1415839f7acbf74f335c4a9f81f76097bb | Error
[10:44:27] e264c56808c7bca4f54f606d16c923982d8653e8 | Error
[10:44:27] 8a8ac13a07ab073be34db8a083c1b34a3ef0e59a | Error
[10:44:27] 0ceeaa46936b939ad0a2eca1b8ee0e5ae854c8f5 | Error

Nodes running fine:
┌─────────────────────────────────────────────┬─────────┬──────────┬──────────┬─────────┬───────────────┬─────────┬──────────┬───────────┬──────────────┐
│ Node                                        │ Status  │ Uptime   │ Restarts │ Peers   │ Allocs        │ Delta   │ Port     │ Shared    │ Bridges      │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 8a8ac13a07ab073be34db8a083c1b34a3ef0e59a    │ running │ 6d 18h … │ 0        │ 42      │ 27            │ 13ms    │ 4051     │ 314.71GB  │ connected    │
│   → /home/sonmtest1070a/Storj2/storjshare   │         │          │          │         │ 0 received    │         │ (TCP)    │ (11%)     │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ fe89ba1415839f7acbf74f335c4a9f81f76097bb    │ running │ 6d 18h … │ 0        │ 18      │ 31            │ 4ms     │ 4052     │ 182.06GB  │ connected    │
│   → /home/sonmtest1070a/Storj3/storjshare   │         │          │          │         │ 4 received    │         │ (TCP)    │ (6%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 984acad726f809fb310208f17e83f81f86c27b54    │ running │ 6d 18h … │ 0        │ 78      │ 25            │ 1ms     │ 4053     │ 239.05GB  │ connected    │
│   → /home/sonmtest1070a/Storj4/storjshare   │         │          │          │         │ 4 received    │         │ (TCP)    │ (8%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 0ceeaa46936b939ad0a2eca1b8ee0e5ae854c8f5    │ running │ 6d 18h … │ 0        │ 85      │ 15            │ 5ms     │ 4054     │ 249.43GB  │ connected    │
│   → /home/sonmtest1070a/Storj5/storjshare   │         │          │          │         │ 2 received    │         │ (TCP)    │ (9%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ e264c56808c7bca4f54f606d16c923982d8653e8    │ running │ 6d 18h … │ 0        │ 32      │ 36            │ 5ms     │ 4050     │ 281.54GB  │ connected    │
│   → /home/sonmtest1070a/Storj1/storjshare   │         │          │          │         │ 0 received    │         │ (TCP)    │ (10%)     │              │
└─────────────────────────────────────────────┴─────────┴──────────┴──────────┴─────────┴───────────────┴─────────┴──────────┴───────────┴──────────────┘

which logs you need?

**Comment by phithor** [comment]
The issue came from a docker image. I think the reason was only that the docker initializing script did not add the API correctly. My issue is resolved. @mirnyyy can you check if your setup is correct? 
I think the monitor should provide a more descriptive error message, an API key mistake is easy to discover in the script i would assume.

**Comment by stefanbenten** [comment]
Did you guys enter your API Key correctly?

**Comment by mirnyyy** [comment]
I think so, I typed API exactly the same way as in Win7. Windows is working, but Ubuntu won't.

**Comment by stefanbenten** [comment]
@mirnyyy Please check the key being present correctly on your ubuntu machines, i am fairly sure thats the issue, why it is throwing an error.

**Comment by stefanbenten** [comment]
Closing this ticket as there are no new updates.
