### ISSUE TITLE
Unable to run on linux with included node_modules

### ISSUE THREAD

**Issue by joe-pritchard** [calxibe/StorjMonitor#4]
On my Ubuntu server, the node modules included in the repo are not valid, and the app refuses to run. The solution to this is just to remove node_modules from the repo and run npm install after cloning locally

**Comment by audioeng** [comment]
Yep, that is correct. I think this was originally designed to work with windows without having to install node or npm, so it contained precompiled windows libraries.

**Comment by sibblegp** [comment]
Same problem.  I want to destroy that leaderboard :)

**Comment by sibblegp** [comment]
`rm -rf node_modules/bindings
rm -rf node_modules/weak
npm install bindings
npm install weak
npm start`

**Comment by audioeng** [comment]
rm -rf node_modules
npm install

Is much less typing....

**Comment by stefanbenten** [comment]
Added the needed Steps to an Install Routine! #9
