### ISSUE TITLE
Not able to run Monitor

### ISSUE THREAD

**Issue by aeonaura** [calxibe/StorjMonitor#5]
![error](https://user-images.githubusercontent.com/35913290/36087199-5940a11a-0f8e-11e8-8383-52ab0666fd6b.PNG)

This is the error I'm getting when I add the API key. What am I doing wrong here?

Thanks

**Comment by joe-pritchard** [comment]
You need to surround the key with quotes :)

**Comment by aeonaura** [comment]
I was running with and without " " and failed. However! You are correct, I believe the API Key need some time to become available. Thanks for the quick response!
