### ISSUE TITLE
Unable to run on Raspberry Pi

### ISSUE THREAD

**Issue by venanx** [calxibe/StorjMonitor#6]
Receiving the error : 

/home/pi/StorjMonitor-master/storjMonitor.js:6
const dnode = require('dnode');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by audioeng** [comment]
Considering that storjshare is not supported on the Pi, I don't think this
is an issue.

**Comment by fbitti** [comment]
Yes, it is: https://docs.storj.io/v1.1/docs/setting-up-storj-share-on-a-raspberry-pi

**Comment by calxibe** [comment]
I don't have much experience with Rasbian myself, but the only file you actually need to run the monitor is storjMonitor.js. You could try to install the dependencies manually and see if you get it up and running.

According to your error log above the Rasbian have a problem with two of the following:
* Running "dnode"
* Incorrect version of Node.js that don't support using "const" (never experienced this before)

**Comment by audioeng** [comment]
please consider buying the Pine Rock64 4GB RAM board here
<https://www.pine64.org/?product=rock64-media-board-computer> instead (all
steps in this guide are still valid),

**Comment by ivnmad** [comment]
When I try to run storjMonitor.sh on Raspberry Pi, I get the following error message

/StorjMonitor-master/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /StorjMonitor-master/node_modules/weak/build/Release/weakref.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/StorjMonitor-master/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/StorjMonitor-master/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by ivnmad** [comment]
If I try to run storjMonitor.js, I get the following error message:

  File "storjMonitor.js", line 6
    const dnode = require('dnode');
              ^
SyntaxError: invalid syntax

**Comment by audioeng** [comment]
What happens if you try changing const to var?

**Comment by ivnmad** [comment]
Same error message:

  File "storjMonitor.js", line 6
    var dnode = require('dnode');
            ^
SyntaxError: invalid syntax

**Comment by 0xBEAKER** [comment]
I'm having the same issue as @ivnmad

**Comment by audioeng** [comment]
Hmm, I don’t know what syntax error that could be..

What version of node?
node —version

**Comment by ivnmad** [comment]
pi@RaspberryPi:~ $ node -v
v8.9.4

**Comment by stefanbenten** [comment]
You need to recompile the preconfigured node_modules. Then it should run without issues @ivnmad , @venanx

**Comment by ivnmad** [comment]
Might need help with this.. I tried to run "npm rebuild node_modules/" and it seem to be successful, but if I then try to run ./storjMonitor.sh I get the same identical error message..

**Comment by ivnmad** [comment]
@stefanbenten making progress.. I followed the instructions, and the installation worked, but..

If I try to run storjMonitor.sh it hangs here (correct API-Key, reporting correct node that I'm deleting):

[14:02:41] xxxxx | Submit to Storjstat
[14:02:41] ERROR {"error":"Invalid farmer data (spaceUsedBytes)"}

Any suggestions?

**Comment by stefanbenten** [comment]
@ivnmad Take a look at this issue, its an error when your storjshare status output doesnt report the used Space correctly: #7 

Your Monitor is working correctly at this point.
I will work on a solution for the above mentioned error 👍
